#page title
page_title                                : Tamga                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : NjBbjvQM                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://erdaltoprak.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/tamga_icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Tamga                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : An offline first nostr contact & profile manager for iOS!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Erdal                                
your_link                                 : https://erdaltoprak.com                     
your_city                                 : France                                
# email_address                             : 
# facebook_username                         :                                           
# instagram_username                        : 
twitter_username                          : erdalxtoprak
github_username                           : erdaltoprak
# youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Offline Ready
    description                           : Browse your Nostr contacts without being always online.
    fontawesome_icon_name                 : star

  - title                                 : Open Source
    description                           : The entire codebase for the app is accessible.
    fontawesome_icon_name                 : star
    
  - title                                 : Privacy First
    description                           : The app doesn't have any ads or trackers, all the content is retreived through open relays.
    fontawesome_icon_name                 : mobile

  - title                                 : Safe Keys
    description                           : Your keys are stored on the device's keychain.
    fontawesome_icon_name                 : play-circle

  - title                                 : Dark Mode
    description                           : NostrID supports Light/Dark mode.
    fontawesome_icon_name                 : adjust

  - title                                 : Nostr Micro Apps Integration
    description                           : Tamga benefits from other nostr apps on the ecosystem for a better user experience.
    fontawesome_icon_name                 : link



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpeg                   
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.2

device_color                              : black                                     

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
